# NumPy Pre-Class Exercises 

We've learned about NumPy and Numpy built-in methos. Let's test your knowledge. (Refer to the pre-class video for the answers)

Import Numpy

In [2]:
import numpy as np

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [6]:
my_list=[1,2,3,4]
my_list

[1, 2, 3, 4]

In [7]:
np.array(my_list)

array([1, 2, 3, 4])

In [9]:
my_matrix=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [10]:
np.array(my_matrix)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(0,13,3)

array([ 0,  3,  6,  9, 12])

### zeros and ones

Generate arrays of zeros or ones

In [5]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [11]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [13]:
np.linspace(0,10, 30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

## eye

Creates an identity matrix

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [15]:
np.random.rand(5)

array([0.02374397, 0.99315973, 0.90107811, 0.97559071, 0.03815728])

In [16]:
np.random.rand(4,4)

array([[0.01083507, 0.46158311, 0.31074889, 0.59977903],
       [0.59681537, 0.16480615, 0.55922603, 0.14261111],
       [0.46461627, 0.32266168, 0.45573802, 0.77850585],
       [0.92262181, 0.3287074 , 0.36901529, 0.04386589]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [17]:
np.random.randn(3)

array([ 2.33426837, -0.03567818,  0.11533714])

In [18]:
np.random.randn(4,4)

array([[-0.02499035,  2.23252396,  0.66909774, -0.05057821],
       [-1.14223361,  0.62766205, -0.19270927,  1.66667067],
       [ 0.34483859, -0.76202147,  0.65169865, -1.50739291],
       [ 0.54185203,  0.03613424, -0.71139409, -1.00407174]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [19]:
np.random.randint(1,50)

29

In [20]:
np.random.randint(1,50,10)

array([49, 38,  9, 25,  8, 46, 35,  3, 14, 46])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [21]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr

array([ 5, 16, 43, 31, 44, 23, 38, 18, 19, 22])

## Reshape
Returns an array containing the same data with a new shape.

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [25]:
ranarr

array([ 5, 16, 43, 31, 44, 23, 38, 18, 19, 22])

In [26]:
ranarr.max()

44

In [27]:
ranarr.argmax()

4

In [28]:
ranarr.min()

5

In [29]:
ranarr.argmin()

0

## Shape

Shape is an attribute that arrays have (not a method):

In [30]:
arr.shape

(25,)

In [31]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [32]:
arr.reshape(1,25).shape

(1, 25)

In [33]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [34]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [35]:
arr.dtype

dtype('int32')

# Great Job!